### ISSUE TITLE
Add instagram share tracking

### ISSUE THREAD

**Issue by dylmye** [StoyanDimitrov/remove-tracking-params#3]
Hello,

Instagram tags URLs with a 'igshid' param that tracks who the sender is. Please add this to your block list. Thanks

**Comment by StoyanDimitrov** [comment]
Thank you for reporting it. The next release, scheduled to 26 August, will include this.

**Comment by StoyanDimitrov** [comment]
Fixed with 757ac5ec9652aa30d7c27c0723a97f19050d25e8
